arch:
  - arm64

language: bash

services:
  - docker

script:
  - docker build --build-arg BASE_IMAGE=arm32v6/alpine --build-arg QEMU_ARCH=arm -t node-arm .
  - docker run --rm -e NODE_VERSION=14.15.0 -v $(pwd)/out:/out node-arm
  - ls -la out
