name: Create Release

on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'Node.js Version'     
        required: true

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.event.inputs.version }}
          release_name: Release ${{ github.ref }}
          body: |
            Node.js v${{ github.event.inputs.version }}
          prerelease: true